[phases.setup]
nixPkgs = ["chromium", "chromedriver", "xvfb-run"]

[phases.install]
cmds = [
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "echo 'Build completed'"
]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120"
